project:
  owner: quickstart-eng@amazon.com
  name: quickstart-dotnet-devenvironment-setup
  parameters:
    KeyName: $[taskcat_getkeypair]
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  # reporting: true
tests:
  devbox:
    parameters:
      KeyName: $[taskcat_getkeypair]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
    template: templates/dev-box.template.yaml
    regions:
    - us-east-1